spring.application.name=servlet

# 실습 2-2에서 원본 HTTP 요청 메시지를 볼 때만 아래 줄의 # 을 지운다 (로그가 매우 많아짐)
# logging.level.org.apache.coyote.http11=trace

# 뷰 리졸버 설정: 논리 이름 앞뒤에 붙일 경로와 확장자
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
